name = "customer-manager"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[vars]
# ADD THIS LINE:
CLOUDFLARE_ZONE_NAME = "chromebased.net" # e.g., pavol-eisenberg.workers.dev
WORKER_API_TOKEN = "0%7wQk0#KgUtbl3O"



# 1. D1 Database Binding

[[d1_databases]]
binding = "DB"
database_name = "root5" # The name you gave your D1 db
database_id = "62c53071-3fce-4861-bfd2-593707ee6716"

# 2. Service Bindings to your other workers
[[services]]
binding = "DNS_SERVICE"
service = "dns-manager" # The name of your DNS worker

[[services]]
binding = "TUNNEL_SERVICE"
service = "tunnel-service" # The name of your Tunnel worker


[[services]]
binding = "ZEROTRUST_SERVICE"
service = "zerotrust-service"

[assets]
binding = "HTML_PAGES"
directory = "./public"
