name = "zerotrust-service"
main = "src/index.ts"
compatibility_date = "2025-10-19"
workers_dev = false
routes = [
  { pattern = "api.chromebased.net/zerotrust/*", zone_name = "chromebased.net" }
]
# Optional but cleaner output
compatibility_flags = [ "nodejs_compat" ]

[vars]
CLOUDFLARE_API_TOKEN = "IL7KAfoxGmETXNFYsbHK7nrp95FUfRt-Q4b06XtR"
CLOUDFLARE_ACCOUNT_ID = "49de41efa595e159eecc15d50e321189"
ACCESS_APP_UID = "ced229ea-8233-4156-a341-142086363e67"
